version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  reviewers:
  - nanmcpe
  assignees:
  - nanmcpe
  ignore:
  - dependency-name: date-fns
    versions:
    - 2.17.0
    - 2.18.0
    - 2.20.0
    - 2.20.1
    - 2.20.2
    - 2.20.3
    - 2.21.0
  - dependency-name: console-stamp
    versions:
    - 3.0.1
  - dependency-name: sequelize
    versions:
    - 6.5.0
    - 6.5.1
    - 6.6.1
  - dependency-name: qs
    versions:
    - 6.10.0
    - 6.9.6
